summary: XML-based font configuration tools
web-url: https://wiki.freedesktop.org/www/Software/fontconfig
git-url: https://gitlab.freedesktop.org/fontconfig/fontconfig
src-url: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.18.3/fontconfig-2.18.3.tar.gz
src-sha: 9ae01e1d53acdef56010c5451cd34aa41d325b2faccd8606448d8fa01b2496b3
license: MIT
dep-pkg: libfreetype libexpat libintl
dep-lib: libintl
dep-upp: gettext-tools python3 gperf

install: |
    mesonw \
        -Ddefault_library=static \
        -Ddoc=disabled \
        -Dtests=disabled \
        -Dtools=enabled \
        -Dcache-build=disabled

dotweak: rm -rf include/ lib/
