summary: XML-based font configuration library
web-url: https://wiki.freedesktop.org/www/Software/fontconfig
git-url: https://gitlab.freedesktop.org/fontconfig/fontconfig
src-url: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.18.3/fontconfig-2.18.3.tar.gz
src-sha: 9ae01e1d53acdef56010c5451cd34aa41d325b2faccd8606448d8fa01b2496b3
license: MIT
dep-pkg: libfreetype libexpat libiconv
dep-upp: gperf python3

install: |
    mesonw \
        -Dnls=disabled \
        -Diconv=enabled \
        -Dtests=disabled \
        -Dtools=disabled
