summary: Cross-platform program for developing Haskell projects
web-url: https://haskellstack.org/
src-url: https://github.com/commercialhaskell/stack/archive/refs/tags/v3.9.3.tar.gz
src-sha: 144bc7eaaf384228f6b0f960ced130b503dc4945ffa42f3ca2037abbc8136c05
license: BSD-3-Clause
bsystem: cabal
dopatch: gsed -i '/^import:/d' cabal.project
