name: ci5 

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  build1:
    if: false

    strategy:
      fail-fast: false
      matrix:
        #target: [ 'MacOSX-10.15-x86_64', 'MacOSX-11.0-x86_64', 'MacOSX-12.0-x86_64', 'MacOSX-13.0-x86_64', 'MacOSX-11.0-arm64', 'MacOSX-12.0-arm64', 'MacOSX-13.0-arm64', 'iPhoneOS-11.0-arm64e', 'iPhoneOS-11.0-arm64' ]
        target: [ 'MacOSX-14.0-arm64' ]
        pkg: [proj,proj7,psc-package,psimd,psutils,pup,putty,pv,pybind11,python@3.10,python@3.11,python@3.12,python@3.9,q,qemu,qpdf,qrencode,quiche,quickjs,ragel,rang,ranger,rapidjson,rav1e,rbspy,rclone,re2c,readpe,redis,restic,resvg,rhash,ripgrep,ripgrep-all,rlwrap,rover,rsass,rsign2,rsync,rtmpdump,rtorrent,ruby,ruff,rust-analyzer,rustic,rustup-init,samurai,sassc,scc,sccache,scdoc,screenresolution,sd,shc,shell2http,shellcheck,shellharden,shiori,silicon,simplex-chat,sl,slang,slumber,socat,soundtouch,speex,spirv-tools,sq,sqlite3,stack,starship,stew,sttr,stwolame,stylua,subfinder,superfile,supervisord,suricata,svn-lite,svt-av1,swig,syncthing,sysinfo,szip,t1utils,taglib,tarlz,tbox,tcc,tcl,tcpdump,tcping,tealdeer,tectonic,tengo,termsvg,terragrunt,texinfo,tic,tiff,tig,timg,tinysearch,tlrc,tmux,tokei,toml++,toml11,tor,torsocks,tree,trietool,ttyd,ttygif,ttyrec,tut,tweego,twolame,typos,uctags,unbound,unixodbc,unrar,unxip,unzip,uppm,uppm@0.15.2]

    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/${{ github.ref_name }}/xcpkg
      - run: chmod u+x xcpkg

      - run: ./xcpkg about
      - run: ./xcpkg setup
      - run: ./xcpkg formula-repo-init test https://github.com/leleliu008/xcpkg-formula-repository-offical-core

      - run: mv formula ~/.xcpkg/repos.d/test/

      - run: ./xcpkg install ${{ matrix.target }}/${{ matrix.pkg }}


  build:
    runs-on: macos-15

    strategy:
      fail-fast: false
      matrix:
        pkg: [proj,proj7,psc-package,psimd,psutils,pup,putty,pv,pybind11,python@3.10,python@3.11,python@3.12,python@3.9,q,qemu,qpdf,qrencode,quiche,quickjs,ragel,rang,ranger,rapidjson,rav1e,rbspy,rclone,re2c,readpe,redis,restic,resvg,rhash,ripgrep,ripgrep-all,rlwrap,rover,rsass,rsign2,rsync,rtmpdump,rtorrent,ruby,ruff,rust-analyzer,rustic,rustup-init,samurai,sassc,scc,sccache,scdoc,screenresolution,sd,shc,shell2http,shellcheck,shellharden,shiori,silicon,simplex-chat,sl,slang,slumber,socat,soundtouch,speex,spirv-tools,sq,sqlite3,stack,starship,stew,sttr,stwolame,stylua,subfinder,superfile,supervisord,suricata,svn-lite,svt-av1,swig,syncthing,sysinfo,szip,t1utils,taglib,tarlz,tbox,tcc,tcl,tcpdump,tcping,tealdeer,tectonic,tengo,termsvg,terragrunt,texinfo,tic,tiff,tig,timg,tinysearch,tlrc,tmux,tokei,toml++,toml11,tor,torsocks,tree,trietool,ttyd,ttygif,ttyrec,tut,tweego,twolame,typos,uctags,unbound,unixodbc,unrar,unxip,unzip,uppm,uppm@0.15.2]

    steps:
      - uses: actions/checkout@v4

      - run: curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/xcpkg-0.30.0-macos-15.0-arm64.release.tar.xz
      - run: /usr/bin/bsdtar xf xcpkg-0.30.0-macos-15.0-arm64.release.tar.xz --strip-components=1

      - run: bin/xcpkg about
      - run: bin/xcpkg sysinfo
      - run: bin/xcpkg formula-repo-init test https://github.com/leleliu008/xcpkg-formula-repository-offical-core

      - run: mv formula ~/.xcpkg/repos.d/test/

      - run: bin/xcpkg install ${{ matrix.pkg }}
