name: check yaml files

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - run: pip install --user yamllint

      - run: yamllint formula
